#ifndef INLINE_WRAPWIN32API_H_
#define INLINE_WRAPWIN32API_H_

#include "stdafx.h"

BOOL GetCommStateWrap(HANDLE, LPDCB, DWORD*);
HANDLE CreateFileWrap(LPCTSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE, DWORD*);
BOOL BuildCommDCBWrap(LPCTSTR, LPDCB, DWORD*);
BOOL SetCommStateWrap(HANDLE, LPDCB, DWORD*);
HANDLE CreateEventWrap(LPSECURITY_ATTRIBUTES, BOOL, BOOL, LPCTSTR, DWORD*);
DWORD WaitForSingleObjectWrap(HANDLE, DWORD, DWORD*);
BOOL GetOverlappedResultWrap(HANDLE, LPOVERLAPPED, LPDWORD, BOOL, DWORD*);
BOOL CancelIoWrap(HANDLE, DWORD*);
DWORD FormatMessageWrap(DWORD, LPCVOID, DWORD, DWORD, LPTSTR, DWORD, DWORD*, va_list*);
#endif
